apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev-services
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: example@baodoemoaks.com
    privateKeySecretRef:
      name: letsencrypt-dev-services
    solvers:
      - http01:
          ingress:
            class: nginx
